eureka: 
  client: 
    serviceUrl:
      defaultZone: https://eureka-server-registry.herokuapp.com/eureka
    registerWithEureka: true
    fetchRegistry: true
    
  instance: 
     preferIpAddress: true
server:
   port: 8079
